POLICY = {
    "USD_CURRENCY": "CONVERT_USD_TO_INR",
    "NEGATIVE_AMOUNT": "TREAT_AS_REFUND",
    "DUPLICATE_ROW": "KEEP_FIRST",
    "UNKNOWN_MEMBER": "FLAG_AND_INCLUDE",
    "INVALID_SPLIT": "FALLBACK_EQUAL_SPLIT"
}